services:
  # Backend FastAPI Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: portfolio_backend
    restart: unless-stopped
    environment:
      MONGO_URL: ${MONGO_URL}
      DATABASE_NAME: ${DATABASE_NAME:-portfolio_db}
      PYTHONPATH: /app
      PYTHONUNBUFFERED: 1
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend React Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        GEMINI_API_KEY: ${GEMINI_API_KEY}
    container_name: portfolio_frontend
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://localhost:8001/api
      REACT_APP_BACKEND_URL: http://localhost:8001
      REACT_APP_GEMINI_API_KEY: ${GEMINI_API_KEY}
    ports:
      - "3000:80"