services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: portfolio_mongodb_dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ${DATABASE_NAME:-portfolio_db}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_dev_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - portfolio_network

  # Backend FastAPI Service - Development Mode
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: portfolio_backend_dev
    restart: unless-stopped
    environment:
      MONGO_URL: mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-password}@mongodb:27017/${DATABASE_NAME:-portfolio_db}?authSource=admin
      DATABASE_NAME: ${DATABASE_NAME:-portfolio_db}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      PYTHONPATH: /app
      PYTHONUNBUFFERED: 1
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
    networks:
      - portfolio_network
    command:
      [
        "uvicorn",
        "server:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8001",
        "--reload",
      ]

  # Frontend React Service - Development Mode
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: portfolio_frontend_dev
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://localhost:8001/api
      REACT_APP_BACKEND_URL: http://localhost:8001
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - portfolio_network
    command: ["npm", "start"]

  # MongoDB Express - Database Admin Interface
  mongo-express:
    image: mongo-express:latest
    container_name: portfolio_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME:-admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD:-password}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-password}@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb
    networks:
      - portfolio_network

# Networks
networks:
  portfolio_network:
    driver: bridge

# Volumes
volumes:
  mongodb_dev_data:
    driver: local
